name: Run SP start script
on:
  workflow_dispatch:

jobs:
  bash-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run SP start script
        run: bash ui-test-auto/SP_WITH_PYTHON/execute_test.sh
